### ISSUE TITLE
Doesn't activate when pressed by touchscreen.

### ISSUE THREAD

**Issue by Cobeta-beta** [markocic/clown-extension#2]
And, that's it.

**Comment by markocic** [comment]
@Cobeta-beta Could you try now? I don't have any touchscreen devices so I can't really test this.

 Follow the steps below if you need help running the latest commit.
1. Remove the official release.
2. clone this repo.
3. run `cd clown@markocic && make install`
4. Logout and log back in.

**Comment by Cobeta-beta** [comment]
So, as far as I know, you updated extension. And if that fix included, then, it doesn’t work. Sound plays only when you hold down the icon.

**Comment by Cobeta-beta** [comment]
> 3\. make install

make: tsc: No such file, or directory 
make: *** [Makefile:12: dist/extension.js] Error 127
